# Generated by Django 3.1.7 on 2021-03-07 19:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('name', models.CharField(default='None', max_length=200, verbose_name='Full Name')),
                ('email', models.CharField(default='None', max_length=200, unique=True, verbose_name='Email')),
                ('address1', models.CharField(max_length=30, null=True, verbose_name='Address')),
                ('address2', models.CharField(default=' ', max_length=100, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=30)),
                ('states', models.CharField(max_length=30, verbose_name='State Name')),
                ('postal_code', models.CharField(max_length=6, null=True, verbose_name='Enter PIN Code')),
                ('country', models.CharField(default='India', max_length=30, verbose_name='Country Name')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9876543210'. Up to 10 digits allowed.", regex='^\\d{10}$')])),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_st', models.DateTimeField(auto_now=True)),
                ('otp', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_OTP', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=200, verbose_name='Full Name')),
                ('email', models.CharField(default=' ', max_length=200, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9876543210'. Up to 10 digits allowed.", regex='^\\d{10}$')])),
                ('address1', models.CharField(max_length=30, null=True, verbose_name='Address')),
                ('address2', models.CharField(default=' ', max_length=100, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=30)),
                ('states', models.CharField(max_length=30, verbose_name='State Name')),
                ('postal_code', models.CharField(max_length=6, null=True, verbose_name='Enter PIN Code')),
                ('country', models.CharField(default='India', max_length=30, verbose_name='Country Name')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ship_profile', to='account.userprofile')),
            ],
        ),
    ]
