# Generated by Django 3.1.7 on 2021-03-07 19:30

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='book', max_length=200, verbose_name='Product Name')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='media/product/', verbose_name='image1(768 x 1093)')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='media/product/', verbose_name='image2(768 x 1093)')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='media/product/', verbose_name='image3(768 x 1093)')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='media/product/', verbose_name='image4(768 x 1093)')),
            ],
        ),
        migrations.CreateModel(
            name='banner_index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner1', models.ImageField(blank=True, upload_to='banner', verbose_name='Banner 1(690 x 483)')),
                ('b1_small', models.CharField(blank=True, max_length=200, verbose_name='Banner 1 Small Heading')),
                ('b1_big', models.CharField(blank=True, max_length=200, verbose_name='Banner 1 Big Heading')),
                ('b1_url', models.CharField(blank=True, max_length=200, verbose_name='Banner 1 search url')),
                ('banner2', models.ImageField(blank=True, upload_to='banner', verbose_name='Banner 2(335 x 483)')),
                ('b2_small', models.CharField(blank=True, max_length=200, verbose_name='Banner 2 Small Heading')),
                ('b2_big', models.CharField(blank=True, max_length=200, verbose_name='Banner 2 Big Heading')),
                ('b2_url', models.CharField(blank=True, max_length=200, verbose_name='Banner 2 search url')),
                ('banner3', models.ImageField(blank=True, upload_to='banner', verbose_name='Banner 3(335 x 238)')),
                ('b3_small', models.CharField(blank=True, max_length=200, verbose_name='Banner 3 Small Heading')),
                ('b3_big', models.CharField(blank=True, max_length=200, verbose_name='Banner 3 Big Heading')),
                ('b3_url', models.CharField(blank=True, max_length=200, verbose_name='Banner 3 search url')),
                ('banner4', models.ImageField(blank=True, upload_to='banner', verbose_name='Banner 4(335 x 238)')),
                ('b4_small', models.CharField(blank=True, max_length=200, verbose_name='Banner 4 Small Heading')),
                ('b4_big', models.CharField(blank=True, max_length=200, verbose_name='Banner 4 Big Heading')),
                ('b4_url', models.CharField(blank=True, max_length=200, verbose_name='Banner 4 search url')),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(default='None', max_length=200, verbose_name='Category Name')),
                ('slug', models.SlugField(blank=True, max_length=55, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('email', models.CharField(blank=True, max_length=200, verbose_name='Email')),
                ('subject', models.CharField(blank=True, max_length=300, verbose_name='Subject')),
                ('message', models.TextField(blank=True, max_length=200, verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='None', max_length=200, verbose_name='Sub-category Name')),
                ('slug', models.SlugField(blank=True, max_length=55, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.IntegerField(blank=True, default=0, primary_key=True, serialize=False)),
                ('ProductName', models.CharField(default='None', max_length=200, verbose_name='Product Name')),
                ('short_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Short Description')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description')),
                ('additional_info', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Additional Information')),
                ('price', models.IntegerField(blank=True, default=100, null=True, verbose_name='MRP')),
                ('discount_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Discount Price')),
                ('discount_percent', models.IntegerField(blank=True, default=0, null=True, verbose_name='Discount Percentage')),
                ('gst', models.IntegerField(blank=True, default=0, null=True, verbose_name='GST')),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Tax Amount')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Unit Price(without GST)')),
                ('quantity', models.IntegerField(blank=True, default=0, verbose_name='Quantity in Stock')),
                ('flipkart', models.CharField(blank=True, max_length=200, null=True, verbose_name='Flipkart Link')),
                ('amazon', models.CharField(blank=True, max_length=200, null=True, verbose_name='Amazon Link')),
                ('meta', models.CharField(blank=True, default=None, max_length=100000, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('CategoryName', models.ManyToManyField(related_name='procat', to='home.category', verbose_name='Category Name')),
                ('SubcatName', models.ManyToManyField(related_name='prosubcat', to='home.subcategory', verbose_name='Sub-category Name')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proimages', to='home.all_images', verbose_name='Product Images')),
            ],
        ),
        migrations.CreateModel(
            name='newrelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newrelease_product', to='home.product', verbose_name='Product')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='SubcatName',
            field=models.ManyToManyField(related_name='subcat', to='home.subcategory', verbose_name='Sub-category Name'),
        ),
        migrations.CreateModel(
            name='bestseller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bestseller_product', to='home.product', verbose_name='Product')),
            ],
        ),
    ]
