# Generated by Django 3.1.7 on 2021-03-07 19:37

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='all_images',
            new_name='product_images',
        ),
    ]
