# Generated by Django 3.1.7 on 2021-03-11 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('home', '0005_auto_20210311_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner_index',
            name='b1_big',
        ),
        migrations.RemoveField(
            model_name='banner_index',
            name='b1_small',
        ),
        migrations.RemoveField(
            model_name='banner_index',
            name='b2_big',
        ),
        migrations.RemoveField(
            model_name='banner_index',
            name='b2_small',
        ),
        migrations.RemoveField(
            model_name='banner_index',
            name='b3_big',
        ),
        migrations.RemoveField(
            model_name='banner_index',
            name='b3_small',
        ),
        migrations.RemoveField(
            model_name='banner_index',
            name='b4_big',
        ),
        migrations.RemoveField(
            model_name='banner_index',
            name='b4_small',
        ),
        migrations.AddField(
            model_name='banner_index',
            name='b5_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Banner 5 search url'),
        ),
        migrations.AddField(
            model_name='banner_index',
            name='banner5',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_image5', to=settings.FILER_IMAGE_MODEL, verbose_name='Banner 5(1918 x 997)'),
        ),
        migrations.AddField(
            model_name='banner_index',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='banner_index',
            name='banner1',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_image1', to=settings.FILER_IMAGE_MODEL, verbose_name='Banner 1(1920 x 650)'),
        ),
        migrations.AlterField(
            model_name='banner_index',
            name='banner2',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_image2', to=settings.FILER_IMAGE_MODEL, verbose_name='Banner 2(3840 x 1500)'),
        ),
        migrations.AlterField(
            model_name='banner_index',
            name='banner3',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_image3', to=settings.FILER_IMAGE_MODEL, verbose_name='Banner 3(960 x 401)'),
        ),
        migrations.AlterField(
            model_name='banner_index',
            name='banner4',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_image4', to=settings.FILER_IMAGE_MODEL, verbose_name='Banner 4(960 x 401)'),
        ),
    ]
