# Generated by Django 3.1.7 on 2021-03-24 18:17

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0012_file_mime_type'),
        ('home', '0006_auto_20210311_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Banner name')),
            ],
        ),
        migrations.CreateModel(
            name='banner_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_url', models.CharField(blank=True, max_length=200, verbose_name='Search url')),
                ('banner', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_main', to='filer.file', verbose_name='Banner(1780px X 720px)')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='home.banner')),
            ],
            options={
                'verbose_name': 'banner',
            },
        ),
        migrations.DeleteModel(
            name='banner_index',
        ),
    ]
