# Generated by Django 3.1.7 on 2021-03-24 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('home', '0007_auto_20210324_2347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'banner'},
        ),
        migrations.AddField(
            model_name='banner',
            name='b1_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Banner 1 search url'),
        ),
        migrations.AddField(
            model_name='banner',
            name='b2_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Banner 2 search url'),
        ),
        migrations.AddField(
            model_name='banner',
            name='b3_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Banner 3 search url'),
        ),
        migrations.AddField(
            model_name='banner',
            name='b4_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Banner 4 search url'),
        ),
        migrations.AddField(
            model_name='banner',
            name='b5_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Banner 5 search url'),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner1',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_image1', to=settings.FILER_IMAGE_MODEL, verbose_name='Banner 1(1920 x 650)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner2',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_image2', to=settings.FILER_IMAGE_MODEL, verbose_name='Banner 2(3840 x 1500)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner3',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_image3', to=settings.FILER_IMAGE_MODEL, verbose_name='Banner 3(960 x 401)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner4',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_image4', to=settings.FILER_IMAGE_MODEL, verbose_name='Banner 4(960 x 401)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner5',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_image5', to=settings.FILER_IMAGE_MODEL, verbose_name='Banner 5(1918 x 997)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name'),
        ),
        migrations.DeleteModel(
            name='banner_main',
        ),
    ]
