# Generated by Django 3.1.7 on 2021-03-24 18:49

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0012_file_mime_type'),
        ('home', '0008_auto_20210325_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner1',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_image1', to='filer.file', verbose_name='Banner 1(1920 x 650)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner2',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_image2', to='filer.file', verbose_name='Banner 2(3840 x 1500)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner3',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_image3', to='filer.file', verbose_name='Banner 3(960 x 401)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner4',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_image4', to='filer.file', verbose_name='Banner 4(960 x 401)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner5',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_image5', to='filer.file', verbose_name='Banner 5(1918 x 997)'),
        ),
    ]
