# Generated by Django 3.1.7 on 2021-03-31 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210325_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_cat', to='home.category', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subparent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_sub', to='home.subcategory', verbose_name='Parent'),
        ),
    ]
