# Generated by Django 3.1.7 on 2021-04-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210401_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.CharField(default=' ', max_length=200, verbose_name='Men/Women/Kid'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='tags',
            field=models.CharField(default=' ', max_length=200, verbose_name='Men/Women/Kid'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(default=' ', max_length=200, verbose_name='Sub-category Name'),
        ),
    ]
