# Generated by Django 3.1.7 on 2021-04-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210401_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CategoryName',
            field=models.CharField(default=' ', max_length=200, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductName',
            field=models.CharField(default=' ', max_length=200, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta',
            field=models.CharField(blank=True, default='', max_length=100000, null=True),
        ),
    ]
