# Generated by Django 3.1.7 on 2021-04-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210401_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner1',
            field=models.FileField(blank=True, null=True, upload_to='banner/', verbose_name='Banner 1(1920 x 650)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner2',
            field=models.FileField(blank=True, null=True, upload_to='banner/', verbose_name='Banner 2(3840 x 1500)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner3',
            field=models.FileField(blank=True, null=True, upload_to='banner/', verbose_name='Banner 3(960 x 401)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner4',
            field=models.FileField(blank=True, null=True, upload_to='banner/', verbose_name='Banner 4(960 x 401)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner5',
            field=models.FileField(blank=True, null=True, upload_to='banner/', verbose_name='Banner 5(1918 x 997)'),
        ),
        migrations.AlterField(
            model_name='product_images',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='image1(1860 x 1860)'),
        ),
        migrations.AlterField(
            model_name='product_images',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='image2(1860 x 1860)'),
        ),
        migrations.AlterField(
            model_name='product_images',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='image3(1860 x 1860)'),
        ),
        migrations.AlterField(
            model_name='product_images',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='image4(1860 x 1860)'),
        ),
    ]
