# Generated by Django 3.1.7 on 2021-04-12 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210407_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='tags',
        ),
    ]
