# Generated by Django 3.1.7 on 2021-04-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210419_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Discount Percentage'),
        ),
        migrations.AddField(
            model_name='variants',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Discount Price'),
        ),
        migrations.AddField(
            model_name='variants',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='variants',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='USD'),
        ),
    ]
