# Generated by Django 3.1.7 on 2021-04-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20210419_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='gst',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='GST'),
        ),
        migrations.AddField(
            model_name='variants',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Tax Amount'),
        ),
        migrations.AddField(
            model_name='variants',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Unit Price(without GST)'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='discount_percent',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Discount Percentage'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='discount_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Discount Price'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='price',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='MRP'),
        ),
    ]
