# Generated by Django 3.1.7 on 2021-04-22 12:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210422_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='additional_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Additional Information'),
        ),
        migrations.AddField(
            model_name='variants',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='variants',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, default=10, verbose_name='Quantity in Stock'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='quantity',
            field=models.IntegerField(blank=True, default=10, verbose_name='Quantity in Stock'),
        ),
    ]
