# Generated by Django 3.1.7 on 2021-04-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20210422_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='Additional Information'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Short Description'),
        ),
    ]
