# Generated by Django 3.1.7 on 2021-04-23 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20210422_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='var_product', to='home.product'),
        ),
    ]
