# Generated by Django 3.2 on 2021-09-06 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20210424_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widgets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('image_size', models.CharField(default='1920 x 650', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='banner',
            name='b1_url',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='b2_url',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='b3_url',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='b4_url',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='b5_url',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='banner1',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='banner2',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='banner3',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='banner4',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='banner5',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='name',
        ),
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.FileField(null=True, upload_to='banner/', verbose_name='Banner 1(1920 x 650)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='redirect_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='widget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.widgets'),
        ),
    ]
