# Generated by Django 3.2 on 2021-09-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20210912_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='CategoryName',
            field=models.ManyToManyField(related_name='procat', to='home.Category', verbose_name='Category Name'),
        ),
    ]
