# Generated by Django 3.2 on 2021-09-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20210912_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_images',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='product_images',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product_images',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product_images',
            name='image4',
        ),
        migrations.AlterField(
            model_name='product',
            name='CategoryName',
            field=models.ManyToManyField(related_name='procat', to='home.Category', verbose_name='Category Name'),
        ),
    ]
