# Generated by Django 3.2 on 2021-09-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20210912_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='CategoryName',
            field=models.ManyToManyField(related_name='procat', to='home.Category', verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='product_images',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='product/', verbose_name='image1(1860 x 1860)'),
        ),
    ]
