# Generated by Django 3.2 on 2021-09-21 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20210912_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='CategoryName',
            field=models.ManyToManyField(related_name='procat', to='home.Category', verbose_name='Category Name'),
        ),
        migrations.CreateModel(
            name='SimilarProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_product', to='home.product')),
                ('similar_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
    ]
