# Generated by Django 3.1.7 on 2021-03-07 19:41

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_auto_20210308_0107'),
        ('account', '0002_auto_20210308_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Coupon/', verbose_name='image')),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('discount', models.IntegerField(blank=True, default=0, verbose_name='Coupon Discount Price')),
                ('discount_percent', models.IntegerField(blank=True, default=0, verbose_name='Coupon Discount Percent')),
                ('slug', models.SlugField(blank=True, max_length=55)),
                ('profile', models.ManyToManyField(blank=True, related_name='coupon_user', to='account.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=100, null=True)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('is_initiated', models.BooleanField(blank=True, default=False, null=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_coupon', to='shop.coupon')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_profile', to='account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=60, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
                ('wished_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=120)),
                ('order_id', models.CharField(max_length=120, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=65, null=True)),
                ('success', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('checksum', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default=None, max_length=200, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OrderItem', to='shop.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prod_order_item', to='home.product')),
            ],
        ),
        migrations.CreateModel(
            name='invoiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=300, null=True, verbose_name='Order ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('nameDetail', models.CharField(max_length=30, null=True, verbose_name='Name')),
                ('email', models.CharField(default='None', max_length=200, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9876543210'. Up to 10 digits allowed.", regex='^\\d{10}$')])),
                ('full_address', models.CharField(max_length=300, null=True, verbose_name='Shipping Address')),
                ('address2', models.CharField(max_length=300, null=True, verbose_name='Address Line 2 ')),
                ('city', models.CharField(max_length=30, null=True, verbose_name='City')),
                ('states', models.CharField(max_length=30, null=True, verbose_name='State')),
                ('pin_code', models.CharField(max_length=30, null=True, verbose_name='PIN Code')),
                ('billing_address', models.TextField(null=True, verbose_name='Billing Address')),
                ('gst_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='GST Number')),
                ('success', models.BooleanField(default=False)),
                ('order_item', models.ManyToManyField(default='Other', related_name='order_items', to='shop.OrderItem')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.userprofile')),
                ('transaction_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Confirmed Order', 'Confirmed Order'), ('Processing Order', 'Processing Order'), ('Quality Check', 'Quality Check'), ('Product Dispatched', 'Product Dispatched'), ('Product Delivered', 'Product Delivered')], default='Confirmed Order', max_length=256)),
                ('shipped_via', models.CharField(default='DTDC', max_length=500, verbose_name='Shipped Via')),
                ('tracking_no', models.CharField(default='0', max_length=500, verbose_name='Tracking Number')),
                ('expected_date', models.DateField(default=datetime.date.today, verbose_name='Expected Date')),
                ('orderIds', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.invoicemodel', verbose_name='Transaction Id')),
                ('order_item', models.ManyToManyField(default='Other', related_name='del_order_items', to='shop.OrderItem')),
                ('orderid1', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order', verbose_name='Order Number')),
            ],
        ),
    ]
