# Generated by Django 3.1.7 on 2021-04-21 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_product_variant'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shipping_charges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Shipping charges')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='device',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.variants'),
        ),
        migrations.AddField(
            model_name='order',
            name='shippingcharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ship_charge', to='shop.shipping_charges', verbose_name='Shipping Charge'),
        ),
    ]
