# Generated by Django 3.2 on 2021-06-20 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20210424_0001'),
        ('shop', '0002_auto_20210421_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='var_order_item', to='home.variants'),
        ),
    ]
